export type Role = "super_admin" | "admin" | "humas";
export type Status = "Menunggu" | "Perlu revisi" | "Diterima" | "Ditolak";
export type School = {
  id: string;
  name: string;
  short_name: string;
  tagline: string;
  intro: string;
  principal_name: string;
  principal_message: string;
  principal_image: string;
  vision: string;
  mission: string[];
  phone: string;
  email: string;
  address: string;
  maps_url: string;
  academic_year: string;
  ppdb_open: boolean;
  ppdb_start: string;
  ppdb_end: string;
  maintenance: boolean;
};
export type Post = {
  id: string;
  title: string;
  slug: string;
  category: string;
  body: string;
  image: string;
  published: boolean;
  pinned: boolean;
  created_at: string;
  author_id?: string;
};
export type Announcement = {
  id: string;
  title: string;
  body: string;
  pinned: boolean;
  created_at: string;
};
export type GalleryItem = {
  id: string;
  title: string;
  image: string;
  category: string;
  created_at: string;
};
export type Registration = {
  id: string;
  registration_number: string;
  student_name: string;
  nisn: string;
  birth_date: string;
  gender: string;
  parent_name: string;
  parent_phone: string;
  email: string;
  address: string;
  previous_school: string;
  status: Status;
  notes: string;
  report_path: string;
  birth_path: string;
  created_at: string;
  updated_at: string;
};
export type ActionResult = { error?: string; success?: string };
